
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.MovieBooking.view;

import com.MovieBooking.model.MovieModel; // Make sure you import MovieModel
import java.util.LinkedList;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import com.MovieBooking.util.validationUtil;

public class MovieBooking extends javax.swing.JFrame {

    private LinkedList<MovieModel> movieList; // Use MovieModel here
    private java.awt.CardLayout cardLayout;
    private final Color errorColor = new Color(255, 0, 0); // Red for errors
    private final Color yellowColor = new Color(255, 255, 0); // Yellow for highlighting

    // Constructor
    public MovieBooking() {
        initComponents();
        initializeLayout();
        movieList = new LinkedList<>();  // Make sure movieList is initialized
        initializeData();  // If you have any initial data loading method
        startProgress();
    }

    private void showDialogBox(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }

    //loadscreen
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }

    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        getContentPane().add(loadingscreenpnl, "LoadingScreen");
        getContentPane().add(loginscreenpnl, "LoginScreen");
        getContentPane().add(mainscreenpnl, "MainScreen");

        // Start with the loading screen
        loadScreen("LoadingScreen");
    }

    private void initializeData() {
        movieList = new LinkedList<>();
        registermovie(new MovieModel(1234567, "Dawa Balami", "dawa@gmail.com", "9862737491", "Crazy Rich Asians", "1:30 PM", "A1", "Sunday"));
        registermovie(new MovieModel(5678912, "Mary Lama", "mary@gmail.com", "9860097032", "Harry Potter", "1:30 PM", "A2", "Sunday"));
    }

    // This method starts the progress bar
    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                loadingbarpg.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen
            }
        };
        worker.execute(); // Start the worker thread
    }

    // Register a new movie to the list and update the table
    private void registermovie(MovieModel movie) {
        movieList.add(movie); // Add movie to the list
        DefaultTableModel model = (DefaultTableModel) movietbl.getModel(); // Get the table model
        model.addRow(new Object[]{
            movie.getName(), // Access name
            movie.getBookingID(), // Access booking ID
            movie.getEmail(), // Access email
            movie.getContact(), // Access contact
            movie.getMovie(), // Access movie
            movie.getShowTime(), // Access show time
            movie.getSeatNumber(), // Access seat number
            movie.getDate() // Access date
        });
    }

//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainscreenpnl2 = new javax.swing.JPanel();
        JTPframe2 = new javax.swing.JTabbedPane();
        JPNLhome2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        JPLmoana2 = new javax.swing.JPanel();
        JLBmoana2 = new javax.swing.JLabel();
        JPLharrypotter = new javax.swing.JPanel();
        JLBharrypotter = new javax.swing.JLabel();
        JPLcrazyrichasian = new javax.swing.JPanel();
        JLBcrazyrichasian = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPLhungergames = new javax.swing.JPanel();
        JBLhungergames = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JPLinsideout = new javax.swing.JPanel();
        JLBinsideout = new javax.swing.JLabel();
        LPNLhtlagi10 = new javax.swing.JPanel();
        JLBLhtlagi10 = new javax.swing.JLabel();
        PNLzootopia = new javax.swing.JPanel();
        JLBLzootopia = new javax.swing.JLabel();
        JPNLSchedule = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        JPNLbooking = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        movietbl = new javax.swing.JTable();
        nametxtfld = new javax.swing.JTextField();
        idtxtfld = new javax.swing.JTextField();
        contacttxtfld = new javax.swing.JTextField();
        emailtxtfld = new javax.swing.JTextField();
        clearbtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        nameerrorlbl = new javax.swing.JLabel();
        iderrorlbl = new javax.swing.JLabel();
        contacterrorlbl = new javax.swing.JLabel();
        emailerrorlbl = new javax.swing.JLabel();
        movieerrorlbl = new javax.swing.JLabel();
        timeerrorlbl = new javax.swing.JLabel();
        seaterrorlbl = new javax.swing.JLabel();
        dateerrorlbl = new javax.swing.JLabel();
        movietxtfld = new javax.swing.JTextField();
        timetxtfld = new javax.swing.JTextField();
        seattxtfld = new javax.swing.JTextField();
        datetxtfld = new javax.swing.JTextField();
        deletebtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JPNLlogo = new javax.swing.JPanel();
        JLBLlogo = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();
        loginscreenpnl = new javax.swing.JPanel();
        usernametxtFld = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        errorlbl = new javax.swing.JLabel();
        passwordFld = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        loadingscreenpnl = new javax.swing.JPanel();
        loadingbarpg = new javax.swing.JProgressBar();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        mainscreenpnl2.setBackground(new java.awt.Color(255, 255, 255));

        JTPframe2.setBackground(new java.awt.Color(255, 255, 204));
        JTPframe2.setForeground(new java.awt.Color(153, 0, 0));

        JPNLhome2.setBackground(new java.awt.Color(204, 177, 139));

        jLabel32.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 51, 0));
        jLabel32.setText("Harry Potter: Half-Blood Prince");

        jLabel33.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 51, 0));
        jLabel33.setText("How to lose a guy in 10 days");

        jLabel34.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 51, 0));
        jLabel34.setText("Zoootopia");

        jLabel35.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 51, 0));
        jLabel35.setText("Inside Out");

        jLabel36.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 51, 0));
        jLabel36.setText("Coming Soon");
        jLabel36.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(153, 0, 0))); // NOI18N

        jLabel37.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 51, 0));
        jLabel37.setText("Showing Now");
        jLabel37.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        JPLmoana2.setPreferredSize(new java.awt.Dimension(111, 151));

        JLBmoana2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/moana.jpg"))); // NOI18N

        javax.swing.GroupLayout JPLmoana2Layout = new javax.swing.GroupLayout(JPLmoana2);
        JPLmoana2.setLayout(JPLmoana2Layout);
        JPLmoana2Layout.setHorizontalGroup(
            JPLmoana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBmoana2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPLmoana2Layout.setVerticalGroup(
            JPLmoana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBmoana2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPLharrypotter.setPreferredSize(new java.awt.Dimension(111, 151));

        JLBharrypotter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/harrypotter (1).jpg"))); // NOI18N

        javax.swing.GroupLayout JPLharrypotterLayout = new javax.swing.GroupLayout(JPLharrypotter);
        JPLharrypotter.setLayout(JPLharrypotterLayout);
        JPLharrypotterLayout.setHorizontalGroup(
            JPLharrypotterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBharrypotter, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        JPLharrypotterLayout.setVerticalGroup(
            JPLharrypotterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBharrypotter, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );

        JPLcrazyrichasian.setPreferredSize(new java.awt.Dimension(111, 151));

        JLBcrazyrichasian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/crazyrichasian (1).jpg"))); // NOI18N

        javax.swing.GroupLayout JPLcrazyrichasianLayout = new javax.swing.GroupLayout(JPLcrazyrichasian);
        JPLcrazyrichasian.setLayout(JPLcrazyrichasianLayout);
        JPLcrazyrichasianLayout.setHorizontalGroup(
            JPLcrazyrichasianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBcrazyrichasian, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        JPLcrazyrichasianLayout.setVerticalGroup(
            JPLcrazyrichasianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBcrazyrichasian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Moana 2");

        jLabel2.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Crazy Rich Asians");

        JPLhungergames.setPreferredSize(new java.awt.Dimension(111, 151));

        JBLhungergames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/hungergameposter (1).jpg"))); // NOI18N

        javax.swing.GroupLayout JPLhungergamesLayout = new javax.swing.GroupLayout(JPLhungergames);
        JPLhungergames.setLayout(JPLhungergamesLayout);
        JPLhungergamesLayout.setHorizontalGroup(
            JPLhungergamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JBLhungergames, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        JPLhungergamesLayout.setVerticalGroup(
            JPLhungergamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JBLhungergames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Hunger Games");

        JPLinsideout.setPreferredSize(new java.awt.Dimension(111, 151));

        JLBinsideout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/insideout.jpg"))); // NOI18N

        javax.swing.GroupLayout JPLinsideoutLayout = new javax.swing.GroupLayout(JPLinsideout);
        JPLinsideout.setLayout(JPLinsideoutLayout);
        JPLinsideoutLayout.setHorizontalGroup(
            JPLinsideoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBinsideout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPLinsideoutLayout.setVerticalGroup(
            JPLinsideoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBinsideout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LPNLhtlagi10.setPreferredSize(new java.awt.Dimension(111, 151));

        JLBLhtlagi10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/howtoloseaguy (1).jpg"))); // NOI18N

        javax.swing.GroupLayout LPNLhtlagi10Layout = new javax.swing.GroupLayout(LPNLhtlagi10);
        LPNLhtlagi10.setLayout(LPNLhtlagi10Layout);
        LPNLhtlagi10Layout.setHorizontalGroup(
            LPNLhtlagi10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBLhtlagi10, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        LPNLhtlagi10Layout.setVerticalGroup(
            LPNLhtlagi10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBLhtlagi10, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );

        PNLzootopia.setPreferredSize(new java.awt.Dimension(111, 151));

        JLBLzootopia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/zootopia (1).jpg"))); // NOI18N

        javax.swing.GroupLayout PNLzootopiaLayout = new javax.swing.GroupLayout(PNLzootopia);
        PNLzootopia.setLayout(PNLzootopiaLayout);
        PNLzootopiaLayout.setHorizontalGroup(
            PNLzootopiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBLzootopia, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        PNLzootopiaLayout.setVerticalGroup(
            PNLzootopiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLzootopiaLayout.createSequentialGroup()
                .addComponent(JLBLzootopia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(157, 157, 157))
        );

        javax.swing.GroupLayout JPNLhome2Layout = new javax.swing.GroupLayout(JPNLhome2);
        JPNLhome2.setLayout(JPNLhome2Layout);
        JPNLhome2Layout.setHorizontalGroup(
            JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNLhome2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNLhome2Layout.createSequentialGroup()
                        .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPLmoana2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPNLhome2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4)))
                        .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPNLhome2Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(JPLharrypotter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNLhome2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)
                                .addGap(99, 99, 99)))
                        .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPNLhome2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addGap(160, 160, 160)
                                .addComponent(jLabel3))
                            .addGroup(JPNLhome2Layout.createSequentialGroup()
                                .addComponent(JPLcrazyrichasian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145)
                                .addComponent(JPLhungergames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNLhome2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36))
                        .addGap(643, 643, 643))))
            .addGroup(JPNLhome2Layout.createSequentialGroup()
                .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNLhome2Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(JPLinsideout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(LPNLhtlagi10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(PNLzootopia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPNLhome2Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel35)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel33)
                        .addGap(166, 166, 166)
                        .addComponent(jLabel34)))
                .addGap(0, 358, Short.MAX_VALUE))
        );
        JPNLhome2Layout.setVerticalGroup(
            JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNLhome2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNLhome2Layout.createSequentialGroup()
                        .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JPLmoana2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPLcrazyrichasian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPLhungergames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(JPNLhome2Layout.createSequentialGroup()
                        .addComponent(JPLharrypotter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)))
                .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNLhome2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(JPLinsideout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNLhome2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LPNLhtlagi10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PNLzootopia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPNLhome2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        JTPframe2.addTab("Home", JPNLhome2);

        JPNLSchedule.setBackground(new java.awt.Color(204, 177, 139));

        jLabel10.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 0));
        jLabel10.setText("How To Lose A Guy In 10 Days");

        jLabel11.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 51, 0));
        jLabel11.setText("Inside Out");

        jLabel13.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 0));
        jLabel13.setText("Zootopia");

        jPanel6.setPreferredSize(new java.awt.Dimension(111, 151));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/howtoloseaguy (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );

        jPanel7.setPreferredSize(new java.awt.Dimension(111, 151));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/insideout.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setPreferredSize(new java.awt.Dimension(111, 151));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/zootopia (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/howtoloseaguyabout (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/insideoutabout (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/zootopiaabout (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPNLScheduleLayout = new javax.swing.GroupLayout(JPNLSchedule);
        JPNLSchedule.setLayout(JPNLScheduleLayout);
        JPNLScheduleLayout.setHorizontalGroup(
            JPNLScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNLScheduleLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPNLScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JPNLScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNLScheduleLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNLScheduleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPNLScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(8, 8, 8))
        );
        JPNLScheduleLayout.setVerticalGroup(
            JPNLScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNLScheduleLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(JPNLScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPNLScheduleLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPNLScheduleLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPNLScheduleLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        JTPframe2.addTab("Schedule", JPNLSchedule);

        JPNLbooking.setBackground(new java.awt.Color(204, 177, 139));

        movietbl.setBackground(new java.awt.Color(255, 255, 204));
        movietbl.setForeground(new java.awt.Color(255, 255, 255));
        movietbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name ", "Booking ID", "Email", " Contact", "Movie ", "Show Time", "Seat Number", "Date"
            }
        ));
        jScrollPane1.setViewportView(movietbl);

        nametxtfld.setBackground(new java.awt.Color(204, 177, 139));
        nametxtfld.setForeground(new java.awt.Color(255, 255, 255));
        nametxtfld.setText(" ");
        nametxtfld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        idtxtfld.setBackground(new java.awt.Color(204, 177, 139));
        idtxtfld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        contacttxtfld.setBackground(new java.awt.Color(204, 177, 139));
        contacttxtfld.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        contacttxtfld.setText(" ");
        contacttxtfld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        emailtxtfld.setBackground(new java.awt.Color(204, 177, 139));
        emailtxtfld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        clearbtn.setBackground(new java.awt.Color(204, 177, 139));
        clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(204, 177, 139));
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(204, 177, 139));
        updatebtn.setForeground(new java.awt.Color(255, 255, 255));
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        movietxtfld.setBackground(new java.awt.Color(204, 177, 139));
        movietxtfld.setForeground(new java.awt.Color(255, 255, 255));
        movietxtfld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        timetxtfld.setBackground(new java.awt.Color(204, 177, 139));
        timetxtfld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        seattxtfld.setBackground(new java.awt.Color(204, 177, 139));
        seattxtfld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        datetxtfld.setBackground(new java.awt.Color(204, 177, 139));
        datetxtfld.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        deletebtn.setBackground(new java.awt.Color(204, 177, 139));
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("Delete");
        deletebtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPNLbookingLayout = new javax.swing.GroupLayout(JPNLbooking);
        JPNLbooking.setLayout(JPNLbookingLayout);
        JPNLbookingLayout.setHorizontalGroup(
            JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNLbookingLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNLbookingLayout.createSequentialGroup()
                .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNLbookingLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(movieerrorlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nametxtfld, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(movietxtfld)
                            .addComponent(nameerrorlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(149, 149, 149)
                        .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iderrorlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idtxtfld, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(timeerrorlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timetxtfld))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contacttxtfld, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(contacterrorlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seaterrorlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seattxtfld))
                        .addGap(171, 171, 171))
                    .addGroup(JPNLbookingLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(clearbtn)
                        .addGap(206, 206, 206)
                        .addComponent(addbtn)
                        .addGap(238, 238, 238)
                        .addComponent(updatebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(emailerrorlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailtxtfld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(dateerrorlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(datetxtfld))
                    .addGroup(JPNLbookingLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112))
        );
        JPNLbookingLayout.setVerticalGroup(
            JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNLbookingLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contacttxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailtxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPNLbookingLayout.createSequentialGroup()
                            .addComponent(contacterrorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNLbookingLayout.createSequentialGroup()
                            .addComponent(nameerrorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)))
                    .addGroup(JPNLbookingLayout.createSequentialGroup()
                        .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iderrorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailerrorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNLbookingLayout.createSequentialGroup()
                        .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPNLbookingLayout.createSequentialGroup()
                                .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(movietxtfld)
                                    .addComponent(timetxtfld))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(JPNLbookingLayout.createSequentialGroup()
                                .addComponent(datetxtfld)
                                .addGap(12, 12, 12)))
                        .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(movieerrorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(timeerrorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dateerrorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPNLbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearbtn)
                            .addComponent(addbtn)
                            .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPNLbookingLayout.createSequentialGroup()
                        .addComponent(seattxtfld)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seaterrorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatebtn)))
                .addGap(42, 42, 42))
        );

        JTPframe2.addTab("Booking", JPNLbooking);

        jPanel3.setBackground(new java.awt.Color(204, 177, 139));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/contactus (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        JTPframe2.addTab("Contact Us", jPanel3);

        JLBLlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/cineworld (3).jpg"))); // NOI18N

        javax.swing.GroupLayout JPNLlogoLayout = new javax.swing.GroupLayout(JPNLlogo);
        JPNLlogo.setLayout(JPNLlogoLayout);
        JPNLlogoLayout.setHorizontalGroup(
            JPNLlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBLlogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPNLlogoLayout.setVerticalGroup(
            JPNLlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLBLlogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logoutbtn.setBackground(new java.awt.Color(102, 51, 0));
        logoutbtn.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("Log Out");
        logoutbtn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainscreenpnl2Layout = new javax.swing.GroupLayout(mainscreenpnl2);
        mainscreenpnl2.setLayout(mainscreenpnl2Layout);
        mainscreenpnl2Layout.setHorizontalGroup(
            mainscreenpnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTPframe2)
            .addGroup(mainscreenpnl2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JPNLlogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        mainscreenpnl2Layout.setVerticalGroup(
            mainscreenpnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainscreenpnl2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(mainscreenpnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainscreenpnl2Layout.createSequentialGroup()
                        .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainscreenpnl2Layout.createSequentialGroup()
                        .addComponent(JPNLlogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addComponent(JTPframe2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginscreenpnl.setBackground(new java.awt.Color(204, 177, 139));

        jLabel15.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 51, 0));
        jLabel15.setText("Username :");

        jLabel16.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 51, 0));
        jLabel16.setText("Password");

        loginbtn.setBackground(new java.awt.Color(102, 51, 0));
        loginbtn.setFont(new java.awt.Font("Al Bayan", 1, 14)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("Login");
        loginbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 51, 0));
        jLabel18.setText("Sign in To Take Your Seat");

        passwordFld.setText("jPasswordField1");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/cineworld (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout loginscreenpnlLayout = new javax.swing.GroupLayout(loginscreenpnl);
        loginscreenpnl.setLayout(loginscreenpnlLayout);
        loginscreenpnlLayout.setHorizontalGroup(
            loginscreenpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginscreenpnlLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(loginscreenpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginscreenpnlLayout.createSequentialGroup()
                        .addGroup(loginscreenpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernametxtFld)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(passwordFld, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginscreenpnlLayout.createSequentialGroup()
                        .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginscreenpnlLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(loginscreenpnlLayout.createSequentialGroup()
                        .addComponent(errorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        loginscreenpnlLayout.setVerticalGroup(
            loginscreenpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginscreenpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorlbl)
                .addGap(53, 53, 53)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernametxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordFld, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadingscreenpnl.setBackground(new java.awt.Color(255, 255, 255));

        loadingbarpg.setBackground(new java.awt.Color(153, 0, 51));

        jLabel17.setBackground(new java.awt.Color(153, 0, 0));
        jLabel17.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 0, 0));
        jLabel17.setText("Every Great Story Start With A Little Wait  ....");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/MovieBooking/resources/cineworld(2).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout loadingscreenpnlLayout = new javax.swing.GroupLayout(loadingscreenpnl);
        loadingscreenpnl.setLayout(loadingscreenpnlLayout);
        loadingscreenpnlLayout.setHorizontalGroup(
            loadingscreenpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingscreenpnlLayout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addGroup(loadingscreenpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(loadingscreenpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loadingbarpg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(430, 430, 430))
        );
        loadingscreenpnlLayout.setVerticalGroup(
            loadingscreenpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingscreenpnlLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(loadingbarpg, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadingscreenpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadingscreenpnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
//        String username = usernametxtFld.getText();
        String password = new String(passwordFld.getPassword());
        String username = usernametxtFld.getText();

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            errorlbl.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) {
            errorlbl.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            errorlbl.setText(""); // Clear any previous error messages
            loadScreen("MainScreen");
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        passwordFld.setText("");
        usernametxtFld.setText("");
        loadScreen("LoginScreen");
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        try {
            // Assuming 'bookingNo' is analogous to 'BookingID' in your MovieBooking class
            int bookingNo = Integer.parseInt(idtxtfld.getText().trim());  // Using bookingNo instead of kartNo
            boolean found = false;

            // Iterate through the movieList to find the MovieBooking with the specified Booking No
            for (int i = 0; i < movieList.size(); i++) {
                // Assuming getBookingID() is the method in MovieBooking to get the BookingID (or bookingNo)
                if (movieList.get(i).getBookingID() == bookingNo) {
                    // Remove the movie booking from the list
                    movieList.remove(i);
                    found = true;

                    // Update the table
                    loadListToTable(movieList);

                    // Clear the form
                    clearMovieForm();

                    // Show success message
                    showDialogBox("Movie booking deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }

            if (!found) {
                // Show error if the Booking No (BookingID) is not found
                showDialogBox("Booking No not found. Please enter a valid Booking No.", "Error", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // Show error if Booking No is invalid
            showDialogBox("Please enter a valid Booking No.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        try {
            // Get the booking ID from the input field (use the correct field name)
            int bookingID = Integer.parseInt(idtxtfld.getText().trim());
            boolean movieFound = false;

            // Loop through movie list to find the movie with the given booking ID
            for (MovieModel movie : movieList) {
                if (movie.getBookingID() == bookingID) {
                    // Movie found, update their details
                    movie.setName(nametxtfld.getText().trim());
                    movie.setBookingID(Integer.parseInt(idtxtfld.getText().trim()));  // Update with correct ID field
                    movie.setEmail(emailtxtfld.getText().trim());  // Fixed setEmail to emailtxtfld
                    movie.setContact(contacttxtfld.getText().trim());
                    movie.setMovie(movietxtfld.getText().trim());
                    movie.setShowTime(timetxtfld.getText().trim());
                    movie.setSeatNumber(seattxtfld.getText().trim());
                    movie.setDate(datetxtfld.getText().trim());  // Set the correct date field

                    movieFound = true;
                    break;
                }
            }

            // Check if the movie was found and updated
            if (movieFound) {
                loadListToTable(movieList);  // Update the table with the new data

                showDialogBox("Movie information updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                clearMovieForm();  // Clear input fields after successful update
            } else {
                // Movie with the given booking ID not found
                showDialogBox("No movie found with Booking ID: " + bookingID, "Update Failed", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // Show error if the input for Booking ID is not a valid number
            showDialogBox("Please enter a valid Booking ID.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed

        boolean isValid = true;

        try {
            // Validate ID
            isValid &= validateField(
                idtxtfld, "bookingID", iderrorlbl, "Must be a 7-digit number.",
                errorColor, yellowColor, validationUtil.isValidId(idtxtfld.getText())
            );

            // Validate Full Name
            isValid &= validateField(
                nametxtfld, "Name", nameerrorlbl, "Must contain only alphabets.",
                errorColor, yellowColor, validationUtil.isValidName(nametxtfld.getText())
            );

            // Validate Contact
            isValid &= validateField(
                contacttxtfld, "Contact", contacterrorlbl, "Must start with 98 and have 10 digits.",
                errorColor, yellowColor, validationUtil.isValidContact(contacttxtfld.getText())
            );

            // Validate Email
            isValid &= validateField(
                emailtxtfld, "Email", emailerrorlbl, "Must be a valid email address.",
                errorColor, yellowColor, validationUtil.isValidEmail(emailtxtfld.getText())
            );

            // Validate Movie Name
            isValid &= validateField(
                movietxtfld, "Movie", movieerrorlbl, "Movie name cannot be empty.",
                errorColor, yellowColor, !movietxtfld.getText().trim().isEmpty()
            );

            // Validate Time
            isValid &= validateField(
                timetxtfld, "Time", timeerrorlbl, "Must be a valid time format (e.g., 1:30 PM).",
                errorColor, yellowColor, validationUtil.isValidTime(timetxtfld.getText())
            );

            // Validate Seat Number
            isValid &= validateField(
                seattxtfld, "Seat Number", seaterrorlbl, "Seat number cannot be empty.",
                errorColor, yellowColor, !seattxtfld.getText().trim().isEmpty()
            );

            // Validate Date
            isValid &= validateField(
                datetxtfld, "Date", dateerrorlbl, "Date cannot be empty.",
                errorColor, yellowColor, !datetxtfld.getText().trim().isEmpty()
            );

            if (isValid) {
                // Create a MovieModel instance
                MovieModel newMovie = new MovieModel(
                    Integer.parseInt(idtxtfld.getText().trim()),
                    nametxtfld.getText().trim(),
                    contacttxtfld.getText().trim(),
                    emailtxtfld.getText().trim(),
                    movietxtfld.getText().trim(),
                    timetxtfld.getText().trim(),
                    seattxtfld.getText().trim(),
                    datetxtfld.getText().trim()
                );

                // Check for duplicate booking ID
                if (checkDuplicateMovie(newMovie)) {
                    idtxtfld.setBorder(createTitledBorder(errorColor, "Booking ID"));
                    showDialogBox("Booking ID already exists.", "Duplicate Entry", JOptionPane.WARNING_MESSAGE);
                } else {
                    // Add the movie if no duplicate is found
                    movieList.add(newMovie);
                    clearMovieForm();
                    loadListToTable(movieList);
                    idtxtfld.setBorder(createTitledBorder(yellowColor, "Booking ID"));
                    showDialogBox("Movie added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            // Catch any unexpected exceptions
            showDialogBox("An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_addbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        nametxtfld.setText("");
        idtxtfld.setText("");
        emailtxtfld.setText("");
        contacttxtfld.setText("");
        movietxtfld.setText("");
        timetxtfld.setText("");
        seattxtfld.setText("");
        datetxtfld.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    //load list to table
    private void loadListToTable(LinkedList<MovieModel> movieList) {
        DefaultTableModel model = (DefaultTableModel) movietbl.getModel();

        // Clear existing rows if needed
        model.setRowCount(0);

        // Populate the table with student data
        movieList.forEach(movie -> model.addRow(new Object[]{
            movie.getName(),
            movie.getBookingID(),
            movie.getEmail(),
            movie.getContact(),
            movie.getMovie(),
            movie.getShowTime(),
            movie.getSeatNumber(),
            movie.getDate()
        }));
    }

// validate field 
    private boolean validateField(JTextField textField, String fieldName, JLabel errorLbl,
            String errorMsg, Color errorColor, Color successColor, boolean isValidFormat) {

        // Check if the field is empty
        if (validationUtil.isNullOrEmpty(textField.getText())) {
            textField.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText("Field cannot be empty!");
            errorLbl.setVisible(true);
            return false;
        } // Check for valid format (this will be customized based on field)
        else if (!isValidFormat) {
            textField.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText(errorMsg);
            errorLbl.setVisible(true);
            return false;
        } // If valid, set border to success color and hide the error label
        else {
            textField.setBorder(createTitledBorder(successColor, fieldName));
            errorLbl.setVisible(false);
            return true;
        }
    }

//create titled border
    private javax.swing.border.TitledBorder createTitledBorder(Color color, String title) {
        return javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(color, 2),
                title,
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", 1, 12),
                color
        );
    }

    //clear movie form
    private void clearMovieForm() {
        idtxtfld.setText("");         // Clear Booking ID field
        nametxtfld.setText("");       // Clear Full Name field
        contacttxtfld.setText("");    // Clear Contact field
        emailtxtfld.setText("");     // Clear Email field
        movietxtfld.setText("");     // Clear Movie field
        timetxtfld.setText("");      // Clear Show Time field
        seattxtfld.setText("");      // Clear Seat Number field
        datetxtfld.setText("");      // Clear Date field
    }

//checkDuplicateMovie
    private boolean checkDuplicateMovie(MovieModel movie) {
        return movieList.stream()
                .anyMatch(existingMovie -> existingMovie.getBookingID() == movie.getBookingID());
    }

//public static void
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MovieBooking().setVisible(true);

            }
            //app.setVisible(true);
            //app.startProgress();
        });
    }

    /**
     * `
     *
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JBLhungergames;
    private javax.swing.JLabel JLBLhtlagi10;
    private javax.swing.JLabel JLBLlogo;
    private javax.swing.JLabel JLBLzootopia;
    private javax.swing.JLabel JLBcrazyrichasian;
    private javax.swing.JLabel JLBharrypotter;
    private javax.swing.JLabel JLBinsideout;
    private javax.swing.JLabel JLBmoana;
    private javax.swing.JLabel JLBmoana1;
    private javax.swing.JLabel JLBmoana2;
    private javax.swing.JPanel JPLcrazyrichasian;
    private javax.swing.JPanel JPLharrypotter;
    private javax.swing.JPanel JPLhungergames;
    private javax.swing.JPanel JPLinsideout;
    private javax.swing.JPanel JPLmoana;
    private javax.swing.JPanel JPLmoana1;
    private javax.swing.JPanel JPLmoana2;
    private javax.swing.JPanel JPNLSchedule;
    private javax.swing.JPanel JPNLbooking;
    private javax.swing.JPanel JPNLhome;
    private javax.swing.JPanel JPNLhome1;
    private javax.swing.JPanel JPNLhome2;
    private javax.swing.JPanel JPNLlogo;
    private javax.swing.JTabbedPane JTPframe;
    private javax.swing.JTabbedPane JTPframe1;
    private javax.swing.JTabbedPane JTPframe2;
    private javax.swing.JPanel LPNLhtlagi10;
    private javax.swing.JPanel PNLzootopia;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel contacterrorlbl;
    private javax.swing.JTextField contacttxtfld;
    private javax.swing.JLabel dateerrorlbl;
    private javax.swing.JTextField datetxtfld;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel emailerrorlbl;
    private javax.swing.JTextField emailtxtfld;
    private javax.swing.JLabel errorlbl;
    private javax.swing.JLabel iderrorlbl;
    private javax.swing.JTextField idtxtfld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar loadingbarpg;
    private javax.swing.JPanel loadingscreenpnl;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPanel loginscreenpnl;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JPanel mainscreenpnl;
    private javax.swing.JPanel mainscreenpnl1;
    private javax.swing.JPanel mainscreenpnl2;
    private javax.swing.JLabel movieerrorlbl;
    private javax.swing.JTable movietbl;
    private javax.swing.JTextField movietxtfld;
    private javax.swing.JLabel nameerrorlbl;
    private javax.swing.JTextField nametxtfld;
    private javax.swing.JPasswordField passwordFld;
    private javax.swing.JLabel seaterrorlbl;
    private javax.swing.JTextField seattxtfld;
    private javax.swing.JLabel timeerrorlbl;
    private javax.swing.JTextField timetxtfld;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField usernametxtFld;
    // End of variables declaration//GEN-END:variables
}
